version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 3000
      MYSQL_DATABASE: preschool_institution
      MYSQL_USER: vitalii
      MYSQL_PASSWORD: vitalii26
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: